import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Activity, ArrowRight, BarChart3, BedDouble, CalendarCheck, Check, HeartPulse, Menu, Pill, ShieldCheck, Stethoscope, TestTube2, Users, X } from 'lucide-react'

const features = [
  [Users, 'Patient management', 'One complete record from registration to discharge, ready whenever your team needs it.'],
  [CalendarCheck, 'Smart appointments', 'Coordinate doctors, departments and patient visits without missed follow-ups.'],
  [BedDouble, 'OPD & IPD workflows', 'Move patients through consultations, admissions, wards and discharge with clarity.'],
  [TestTube2, 'Lab & diagnostics', 'Track orders, samples and results in one connected workflow.'],
  [Pill, 'Pharmacy control', 'Manage prescriptions, dispensing and inventory with real-time information.'],
  [BarChart3, 'Billing & insights', 'Create clearer bills, monitor collections and make confident decisions.'],
]

export default function Landing() {
  const [open, setOpen] = useState(false)
  return <div className="min-h-screen overflow-hidden bg-[#f7faf8] text-slate-900 selection:bg-emerald-200">
    <header className="absolute inset-x-0 top-0 z-50">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
        <Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-600 text-white shadow-lg"><HeartPulse size={23}/></span><span className="text-xl font-bold tracking-[-.04em]">MedCare<span className="text-emerald-600">Axis</span></span></Link>
        <nav className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex"><a href="#platform" className="hover:text-emerald-700">Platform</a><a href="#why" className="hover:text-emerald-700">Why us</a><a href="#security" className="hover:text-emerald-700">Security</a></nav>
        <div className="hidden items-center gap-3 md:flex"><Link to="/login" className="px-4 py-2 text-sm font-semibold">Sign in</Link><a href="#contact" className="rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white hover:bg-emerald-700">Book a demo</a></div>
        <button onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center rounded-xl border bg-white md:hidden" aria-label="Menu">{open ? <X/> : <Menu/>}</button>
      </div>
      {open && <div className="mx-5 rounded-2xl border bg-white p-4 shadow-xl md:hidden"><a href="#platform" className="block p-3">Platform</a><a href="#why" className="block p-3">Why us</a><Link to="/login" className="mt-2 block rounded-xl bg-emerald-600 p-3 text-center font-semibold text-white">Sign in</Link></div>}
    </header>

    <main>
      <section className="relative pb-20 pt-36 lg:pb-28 lg:pt-44">
        <div className="absolute right-[-12rem] top-[-10rem] h-[34rem] w-[34rem] rounded-full bg-emerald-200/50 blur-3xl"/>
        <div className="relative mx-auto grid max-w-7xl items-center gap-16 px-5 lg:grid-cols-[1.05fr_.95fr] lg:px-8">
          <div><div className="mb-7 inline-flex rounded-full border border-emerald-200 bg-white px-4 py-2 text-sm font-semibold text-emerald-800">Built for modern Indian healthcare</div><h1 className="text-5xl font-bold leading-[1.04] tracking-[-.055em] sm:text-6xl lg:text-7xl">Care flows better when everything <span className="text-emerald-600">connects.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">MedCareAxis brings patients, clinicians and hospital operations onto one calm, intelligent platform—so your team can focus on better care.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#contact" className="inline-flex items-center justify-center gap-2 rounded-full bg-emerald-600 px-7 py-4 font-semibold text-white shadow-xl shadow-emerald-700/20 hover:bg-emerald-700">Book your free demo <ArrowRight size={18}/></a><a href="#platform" className="rounded-full border bg-white px-7 py-4 text-center font-semibold">Explore the platform</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-500">{['Fast onboarding','No hidden complexity','Human support'].map(x=><span key={x} className="flex items-center gap-2"><Check size={16} className="text-emerald-600"/>{x}</span>)}</div></div>
          <div className="relative"><div className="absolute -inset-6 rotate-3 rounded-[2.5rem] bg-emerald-200/60"/><div className="relative overflow-hidden rounded-[2rem] border border-white bg-white p-3 shadow-[0_32px_80px_-32px_rgba(15,55,45,.4)]"><div className="rounded-[1.5rem] bg-slate-950 p-7 text-white"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-emerald-300">Live overview</p><p className="mt-1 text-xl font-semibold">Good morning, City Care</p></div><Activity className="text-emerald-300"/></div><div className="mt-7 grid grid-cols-3 gap-3">{[['124','Patients today'],['18','Admissions'],['92%','Beds tracked']].map(([n,l])=><div key={l} className="rounded-2xl bg-white/[.07] p-4"><p className="text-2xl font-bold">{n}</p><p className="mt-1 text-xs text-slate-400">{l}</p></div>)}</div></div><div className="grid gap-3 p-4 sm:grid-cols-2"><div className="rounded-2xl bg-emerald-50 p-5"><div className="flex justify-between text-sm font-semibold"><span>Patient flow</span><span className="text-emerald-700">+12.4%</span></div><div className="mt-5 flex h-24 items-end gap-2">{[48,64,42,78,68,92,82].map((h,i)=><span key={i} className="flex-1 rounded-t bg-emerald-500" style={{height:`${h}%`}}/>)}</div></div><div className="rounded-2xl border p-5"><p className="text-sm font-semibold">Next appointments</p>{['Riya Kapoor','Arjun Mehta','Sara Patel'].map((x,i)=><div key={x} className="mt-3 flex items-center gap-3 text-xs"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 font-bold">{x.split(' ').map(y=>y[0]).join('')}</span><span className="flex-1">{x}</span><span className="text-slate-400">{['10:30','10:45','11:00'][i]}</span></div>)}</div></div></div><div className="absolute -bottom-7 -left-6 hidden items-center gap-3 rounded-2xl bg-white p-4 shadow-xl sm:flex"><span className="rounded-xl bg-emerald-100 p-3 text-emerald-700"><ShieldCheck/></span><div><p className="text-sm font-bold">Secure by design</p><p className="text-xs text-slate-500">Role-based access</p></div></div></div>
        </div>
      </section>

      <section className="border-y bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 px-5 py-8 sm:grid-cols-4">{[['360°','Patient view'],['15+','Connected modules'],['24/7','Secure access'],['1','Unified platform']].map(([n,l],i)=><div key={l} className={`px-3 text-center ${i?'border-l':''}`}><p className="text-3xl font-bold">{n}</p><p className="mt-1 text-xs uppercase tracking-wider text-slate-500">{l}</p></div>)}</div></section>

      <section id="platform" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-600">One connected platform</p><h2 className="mt-4 text-4xl font-bold tracking-[-.045em] sm:text-5xl">Every department, moving together.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Replace disconnected tools and manual work with a system that gives every team the context they need.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text],i)=><article key={title} className="rounded-3xl border bg-white p-7 transition hover:-translate-y-1 hover:border-emerald-200 hover:shadow-xl"><div className={`grid h-12 w-12 place-items-center rounded-2xl ${i?'bg-emerald-50 text-emerald-700':'bg-emerald-600 text-white'}`}><Icon/></div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>

      <section id="why" className="bg-slate-950 py-24 text-white lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-16 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-400">Designed around care</p><h2 className="mt-4 text-4xl font-bold tracking-[-.045em] sm:text-5xl">Powerful for management. Simple for everyone.</h2><p className="mt-6 text-lg leading-8 text-slate-400">Technology should reduce the load on healthcare teams—not add to it. MedCareAxis makes complex operations feel clear.</p><div className="mt-9 grid gap-5 sm:grid-cols-2">{['Quick to learn','Built to scale','Actionable reports','Reliable support'].map(x=><span key={x} className="flex items-center gap-3 font-semibold"><Check className="text-emerald-400" size={18}/>{x}</span>)}</div></div><div id="security" className="rounded-[2rem] border border-white/10 bg-white/[.05] p-9"><ShieldCheck size={42} className="text-emerald-400"/><h3 className="mt-7 text-2xl font-bold">Your hospital data stays protected.</h3><p className="mt-4 leading-7 text-slate-400">Secure authentication, role-based permissions and auditable activity keep sensitive information in the right hands.</p>{['Granular staff permissions','Tenant-isolated records','Complete audit trail'].map(x=><p key={x} className="mt-5 flex items-center gap-3 text-sm text-slate-300"><ShieldCheck size={17} className="text-emerald-400"/>{x}</p>)}</div></div></section>

      <section id="contact" className="px-5 py-24 lg:py-32"><div className="mx-auto max-w-6xl rounded-[2.5rem] bg-emerald-600 px-6 py-16 text-center text-white shadow-2xl"><Stethoscope className="mx-auto" size={38}/><h2 className="mx-auto mt-6 max-w-2xl text-4xl font-bold tracking-[-.045em] sm:text-5xl">Give your team more time for care.</h2><p className="mt-5 text-lg text-emerald-50">See how MedCareAxis can bring clarity, speed and confidence to your hospital.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="mailto:hello@medcareaxis.com" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-4 font-bold text-emerald-700">Schedule a free demo <ArrowRight size={18}/></a><Link to="/login" className="rounded-full border border-white/30 px-7 py-4 font-bold">Existing customer sign in</Link></div></div></section>
    </main>
    <footer className="border-t bg-white"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 py-8 text-sm text-slate-500 sm:flex-row"><span className="font-bold text-slate-800">MedCareAxis</span><p>© 2026 MedCareAxis. Technology with care at its core.</p><Link to="/login" className="font-semibold">Hospital login</Link></div></footer>
  </div>
}
